### ISSUE TITLE
Grass Slab particles are green instead of the vanilla brown

### ISSUE THREAD

**Issue by MrFantiVideo** [fatlard1993/dirt-slab#10]
Hello,

I found that the particles in the dirt blocks and slabs are not correct. In Minecraft they are brown while in the mod they are green.

<a href="https://s6.gifyu.com/images/DirtSlabParticules.gif"><img src="https://s6.gifyu.com/images/DirtSlabParticules.gif" alt="DirtSlabParticules.gif" border="0" /></a>

(The link redirects to a .gif)

**Comment by fatlard1993** [comment]
![particles](https://s6.gifyu.com/images/DirtSlabParticules.gif)

**Comment by fatlard1993** [comment]
I'm calling out the correct dirt particle. I think this is the color registry thing messing with the particle color somehow.

**Comment by fatlard1993** [comment]
Turns out the tintindex defaults to 0, so I had to explicitly change the tint index for the grass top and overlay. Neat stuff
