### ISSUE TITLE
Random Ticks

### ISSUE THREAD

**Issue by MrFantiVideo** [fatlard1993/dirt-slab#11]
Hello,

I found that when you put two half slab together and add a block on top, it does not transform the two half slab below into dirt.
There is also a graphics bug when this happens with a classic game block.

<a href="https://s6.gifyu.com/images/DirtSlabTicks3a6a1d8f68a4888b.gif"><img src="https://s6.gifyu.com/images/DirtSlabTicks3a6a1d8f68a4888b.gif" alt="DirtSlabTicks3a6a1d8f68a4888b.gif" border="0" /></a>

(I modified the randomTickSpeed to speed up the process.)

**Comment by fatlard1993** [comment]
will be included in the next build: 0.2.0

**Comment by fatlard1993** [comment]
Thanks for this and your other issues. I appreciate the time and effort you put in here.
